### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by as754770178** [awslabs/mxboard#27]
root@gpu05:/opt/package# pip install mxboard
Requirement already satisfied: mxboard in /usr/local/anaconda2/lib/python2.7/site-packages (0.1.0)
Requirement already satisfied: six in /usr/local/anaconda2/lib/python2.7/site-packages (from mxboard) (1.11.0)
Requirement already satisfied: numpy in /usr/local/anaconda2/lib/python2.7/site-packages (from mxboard) (1.13.3)
Requirement already satisfied: Pillow in /usr/local/anaconda2/lib/python2.7/site-packages (from mxboard) (4.2.1)
Requirement already satisfied: protobuf>=3.0.0 in /usr/local/anaconda2/lib/python2.7/site-packages (from mxboard) (3.5.2)
Requirement already satisfied: olefile in /usr/local/anaconda2/lib/python2.7/site-packages (from Pillow->mxboard) (0.44)
Requirement already satisfied: setuptools in /usr/local/anaconda2/lib/python2.7/site-packages (from protobuf>=3.0.0->mxboard) (36.5.0.post20170921)
root@gpu05:/opt/package# python mxboard.py
Traceback (most recent call last):
  File "mxboard.py", line 2, in <module>
    from mxboard import SummaryWriter
  File "/opt/package/mxboard.py", line 2, in <module>
    from mxboard import SummaryWriter
ImportError: cannot import name SummaryWriter
root@gpu05:/opt/package#

This problem has been bothering me for a long time

**Comment by as754770178** [comment]
```
root@gpu05:/home/work# pip install mxnet==1.2.0
Collecting mxnet==1.2.0
  Downloading https://files.pythonhosted.org/packages/45/0e/507d59a4c409c005326a6535e1513828e59b83ea2afb7ae449d14542c6bb/mxnet-1.2.0-py2.py3-none-manylinux1_x86_64.whl (26.1MB)
    100% |████████████████████████████████| 26.1MB 36kB/s
Requirement already satisfied: graphviz<0.9.0,>=0.8.1 in /usr/local/anaconda2/lib/python2.7/site-packages (from mxnet==1.2.0)
Requirement already satisfied: requests<2.19.0,>=2.18.4 in /usr/local/anaconda2/lib/python2.7/site-packages (from mxnet==1.2.0)
Requirement already satisfied: numpy<1.15.0,>=1.8.2 in /usr/local/anaconda2/lib/python2.7/site-packages (from mxnet==1.2.0)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/local/anaconda2/lib/python2.7/site-packages (from requests<2.19.0,>=2.18.4->mxnet==1.2.0)
Requirement already satisfied: idna<2.7,>=2.5 in /usr/local/anaconda2/lib/python2.7/site-packages (from requests<2.19.0,>=2.18.4->mxnet==1.2.0)
Requirement already satisfied: urllib3<1.23,>=1.21.1 in /usr/local/anaconda2/lib/python2.7/site-packages (from requests<2.19.0,>=2.18.4->mxnet==1.2.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/anaconda2/lib/python2.7/site-packages (from requests<2.19.0,>=2.18.4->mxnet==1.2.0)
Installing collected packages: mxnet
  Found existing installation: mxnet 1.1.0
    Uninstalling mxnet-1.1.0:
      Successfully uninstalled mxnet-1.1.0
Successfully installed mxnet-1.2.0
You are using pip version 9.0.1, however version 18.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
root@gpu05:/home/work# pip install --upgrade pip
Collecting pip
  Downloading https://files.pythonhosted.org/packages/5f/25/e52d3f31441505a5f3af41213346e5b6c221c9e086a166f3703d2ddaf940/pip-18.0-py2.py3-none-any.whl (1.3MB)
    100% |████████████████████████████████| 1.3MB 671kB/s
Installing collected packages: pip
  Found existing installation: pip 9.0.1
    Uninstalling pip-9.0.1:
      Successfully uninstalled pip-9.0.1
Successfully installed pip-18.0
root@gpu05:/home/work# pip install mxboard
Collecting mxboard
  Downloading https://files.pythonhosted.org/packages/65/f5/a539f60776144d638bb2cb5b56c767da4359e8236652d29c586476f10a83/mxboard-0.1.0-py2-none-any.whl (47kB)
    100% |████████████████████████████████| 51kB 307kB/s
Requirement already satisfied: six in /usr/local/anaconda2/lib/python2.7/site-packages (from mxboard) (1.11.0)
Requirement already satisfied: numpy in /usr/local/anaconda2/lib/python2.7/site-packages (from mxboard) (1.13.3)
Requirement already satisfied: Pillow in /usr/local/anaconda2/lib/python2.7/site-packages (from mxboard) (4.2.1)
Requirement already satisfied: protobuf>=3.0.0 in /usr/local/anaconda2/lib/python2.7/site-packages (from mxboard) (3.5.2)
Requirement already satisfied: olefile in /usr/local/anaconda2/lib/python2.7/site-packages (from Pillow->mxboard) (0.44)
Requirement already satisfied: setuptools in /usr/local/anaconda2/lib/python2.7/site-packages (from protobuf>=3.0.0->mxboard) (36.5.0.post20170921)
Installing collected packages: mxboard
Successfully installed mxboard-0.1.0
root@gpu05:/home/work# python
Python 2.7.14 |Anaconda custom (64-bit)| (default, Oct 16 2017, 17:29:19)
[GCC 7.2.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import mxboard
>>> from mxboard import SummaryWriter
>>>
root@gpu05:/home/work# cd /opt/package/
root@gpu05:/opt/package# ls
Anaconda3-5.2.0-Linux-x86_64.sh  mxboard  mxboard.py  __pycache__
root@gpu05:/opt/package# python mxboard.py
Traceback (most recent call last):
  File "mxboard.py", line 2, in <module>
    from mxboard import SummaryWriter
  File "/opt/package/mxboard.py", line 2, in <module>
    from mxboard import SummaryWriter
ImportError: cannot import name SummaryWriter
root@gpu05:/opt/package#
```

**Comment by reminisce** [comment]
Change `mxboard.py` to another name. mxboard is the module's name, so cannot be a file name.
