### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'syntax'

### ISSUE THREAD

**Issue by jacky4323** [awslabs/mxboard#29]
Hi,
I follow command in https://github.com/awslabs/mxboard

1. pip install mxboard
2. pip install tensorflow tensorboard
3. tensorboard --help

thanks!

RuntimeError: module compiled against API version 0xc but this version of numpy is 0xa
RuntimeError: module compiled against API version 0xc but this version of numpy is 0xa
Traceback (most recent call last):
  File "/home/jacky4323/.local/bin/tensorboard", line 7, in <module>
    from tensorboard.main import run_main
  File "/home/jacky4323/.local/lib/python2.7/site-packages/tensorboard/main.py", line 40, in <module>
    from tensorboard import default
  File "/home/jacky4323/.local/lib/python2.7/site-packages/tensorboard/default.py", line 34, in <module>
    import tensorflow as tf
  File "/home/jacky4323/.local/lib/python2.7/site-packages/tensorflow/__init__.py", line 22, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/home/jacky4323/.local/lib/python2.7/site-packages/tensorflow/python/__init__.py", line 52, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File "/home/jacky4323/.local/lib/python2.7/site-packages/tensorflow/core/framework/graph_pb2.py", line 15, in <module>
    from tensorflow.core.framework import node_def_pb2 as tensorflow_dot_core_dot_framework_dot_node__def__pb2
  File "/home/jacky4323/.local/lib/python2.7/site-packages/tensorflow/core/framework/node_def_pb2.py", line 15, in <module>
    from tensorflow.core.framework import attr_value_pb2 as tensorflow_dot_core_dot_framework_dot_attr__value__pb2
  File "/home/jacky4323/.local/lib/python2.7/site-packages/tensorflow/core/framework/attr_value_pb2.py", line 15, in <module>
    from tensorflow.core.framework import tensor_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__pb2
  File "/home/jacky4323/.local/lib/python2.7/site-packages/tensorflow/core/framework/tensor_pb2.py", line 15, in <module>
    from tensorflow.core.framework import resource_handle_pb2 as tensorflow_dot_core_dot_framework_dot_resource__handle__pb2
  File "/home/jacky4323/.local/lib/python2.7/site-packages/tensorflow/core/framework/resource_handle_pb2.py", line 22, in <module>
    serialized_pb=_b('\n/tensorflow/core/framework/resource_handle.proto\x12\ntensorflow\"r\n\x13ResourceHandleProto\x12\x0e\n\x06\x64\x65vice\x18\x01 \x01(\t\x12\x11\n\tcontainer\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x11\n\thash_code\x18\x04 \x01(\x04\x12\x17\n\x0fmaybe_type_name\x18\x05 \x01(\tBn\n\x18org.tensorflow.frameworkB\x0eResourceHandleP\x01Z=github.com/tensorflow/tensorflow/tensorflow/go/core/framework\xf8\x01\x01\x62\x06proto3')
TypeError: __init__() got an unexpected keyword argument 'syntax'

**Comment by reminisce** [comment]
Seems it's a problem of using the version of tf not supported by mxboard. Could you upgrade your TensorFlow and TensorBoard to the latest version and try again?
